name: 构建并发布

on:
  push:
    tags:
      - "v*" # 当推送带v前缀的标签时触发，例如v1.0.0
  workflow_dispatch: # 允许手动触发工作流

env:
  GITHUB_ACTIONS: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      DATE: ${{ steps.get_date.outputs.DATE }}
    steps:
      - name: 获取当前日期
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  build-macos:
    name: 构建 macOS (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    needs: [setup]
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: x64
            python-arch: x64
          - os: macos-14
            arch: arm64
            python-arch: arm64

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"
          architecture: ${{ matrix.python-arch }}

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller~=6.13.0

      - name: 构建应用
        run: |
          pyinstaller --name XingTu-core-${{ matrix.arch }} \
                      --onefile \
                      --add-data "XingTu_core:XingTu_core" \
                      --hidden-import=PIL._tkinter_finder \
                      XingTu_core/__main__.py

      - name: 压缩构建结果
        run: |
          cd dist
          7z a -r XingTu-core-macos-${{ matrix.arch }}.7z XingTu-core-${{ matrix.arch }}

      - name: 上传构建结果
        uses: actions/upload-artifact@v4
        with:
          name: XingTu-core-macos-${{ matrix.arch }}
          path: dist/XingTu-core-macos-${{ matrix.arch }}.7z

  build-windows:
    name: 构建 Windows
    runs-on: windows-latest
    needs: [setup]

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller~=6.13.0

      # 删除了 PyTorch CUDA 安装步骤

      - name: 构建应用
        run: |
          pyinstaller --name XingTu-core-win --onefile --add-data "XingTu_core;XingTu_core" XingTu_core/__main__.py

      - name: 压缩构建结果
        run: |
          cd dist
          7z a -r XingTu-core-windows.7z XingTu-core-win.exe

      - name: 上传构建结果
        uses: actions/upload-artifact@v4
        with:
          name: XingTu-core-windows
          path: dist/XingTu-core-windows.7z

  release:
    name: 创建发布
    needs: [setup, build-macos, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: 下载所有构建结果
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 准备发布文件
        run: |
          mkdir -p dist
          cp artifacts/XingTu-core-macos-x64/XingTu-core-macos-x64.7z dist/
          cp artifacts/XingTu-core-macos-arm64/XingTu-core-macos-arm64.7z dist/
          cp artifacts/XingTu-core-windows/XingTu-core-windows.7z dist/
          ls -la dist/

      - name: 创建发布
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          name: Release ${{ needs.setup.outputs.DATE }}
          tag_name: ${{ needs.setup.outputs.DATE }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
